// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS5UcYmAxvKnnodEM2Du_lLDEFfMuMCZg',
    appId: '1:664401750325:web:12f87f14ffb5468d2f447c',
    messagingSenderId: '664401750325',
    projectId: 'mpit-2023',
    authDomain: 'mpit-2023.firebaseapp.com',
    databaseURL: 'https://mpit-2023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mpit-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzE1woml3Hbq4E_Ycr-zN2aT9OdLYz8Ak',
    appId: '1:664401750325:android:5410f115b9f804bc2f447c',
    messagingSenderId: '664401750325',
    projectId: 'mpit-2023',
    databaseURL: 'https://mpit-2023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mpit-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKZHHzJCCVLsVFXS_4RpX9uuQvlCpm86s',
    appId: '1:664401750325:ios:d506a6d24414f5c72f447c',
    messagingSenderId: '664401750325',
    projectId: 'mpit-2023',
    databaseURL: 'https://mpit-2023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mpit-2023.appspot.com',
    iosClientId: '664401750325-u4kq3e7lagm9ndg27col4f33vppjdmro.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpit2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKZHHzJCCVLsVFXS_4RpX9uuQvlCpm86s',
    appId: '1:664401750325:ios:d506a6d24414f5c72f447c',
    messagingSenderId: '664401750325',
    projectId: 'mpit-2023',
    databaseURL: 'https://mpit-2023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mpit-2023.appspot.com',
    iosClientId: '664401750325-u4kq3e7lagm9ndg27col4f33vppjdmro.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpit2023',
  );
}
